pipelines:
  - name: pipelines_run_int_test
    steps:
      - name: PS_Sync_9494_008_001
        type: Bash
        execution:
          onExecute:
            - cd /tmp
            - mkdir -p "jfrog-cli"
            - touch test-pilines.yaml
            - echo "test" >> test-pipelines.yaml
      - name: PS_Sync_9494_008_002
        type: Bash
        configuration:
          inputSteps:
            - name: PS_Sync_9494_008_001
        execution:
          onExecute:
            - cd /tmp
            - mkdir -p "target/pipelines"
            - cd target/pipelines
            - touch make_data
